### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by flotwig** [PantherHackers/PantherBot#69]
Feature: allow aliases to be created for commands 

For example...

 > @arshbot : Mo disagrees stating that it does not allow the code to be readable (pb structure demands that the name of a script dictates the command name) and instead wants the file to be `generate_report.py` which means the command name would be `generate_report`

It would be nice if "generate_report" could be the script name (and the original command name) and then an alias for power users to use, say, "g_r" or "gr" could be dynamically created to point to generate_report.

**Comment by ghost** [comment]
Addressed #82
