### ISSUE TITLE
KeyError on message edit

### ISSUE THREAD

**Issue by bcabio** [PantherHackers/PantherBot#84]
When I edit a message, I get this error 
![screen shot 2017-08-30 at 3 37 05 pm](https://user-images.githubusercontent.com/8402553/29891525-62da4d1a-8d99-11e7-9ff4-7dc0461a7cb6.png)

**Comment by ghost** [comment]
Make sure it's actually a message with the text field

**Comment by ghost** [comment]
"Messages" can be anything from join messages to user typing updates. Check the message type before using any field

**Comment by ghost** [comment]
Addressed in #88
